name: 'Github Action Auto Sign In'
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'
jobs:
  signIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
      - run: yarn start
        env:
          ACCOUNT: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          PROVINCE: ${{secrets.PROVINCE}}
          CITY: ${{secrets.CITY}}
          AREA: ${{secrets.AREA}}
  sendEmail:
    needs: signIn
    steps:
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send Email'
        uses: dawidd6/action-send-mail@master
        with:
          serveraddress: smtp.163.com
          serverport: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: ${{ env.GITHUB_ENV }}的ISP打卡结果
          body: file://./static/index.html
          to: ${{ secrets.MAILUSERNAME }}
          from: ${{ secrets.MAILUSERNAME }}
          content_type: text/html