name: 'Github Action Auto Sign In'
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
      - run: yarn start
        env:
          ACCOUNT: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          PROVINCE: ${{secrets.PROVINCE}}
          CITY: ${{secrets.CITY}}
          AREA: ${{secrets.AREA}}
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: 'Make Static Dir'
        run: mkdir static
        run: ll
      - name: 'Send Email'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: Github Actions—ISP Auto-Sign-In Result Of ${{ env.REPORT_DATE }}
          html_body: file://static/index.html
          to: ${{ secrets.MAILUSERNAME }}
          from: ${{ secrets.MAILUSERNAME }}